name: Lambda Versioning and Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'test-1/**'
      - 'test-2/**'
      - 'test-3/**'
      - 'test-4/**'

jobs:
  detect_and_publish:
    name: Detect Changes and Publish Lambda Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Identify Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Get the current branch name
        id: get-branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"
          echo "::set-output name=branch::$CURRENT_BRANCH"

      - name: Filter Changed Files
        id: filter-changed-files
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep -v -e '.gitignore' -e 'rocro.yml' | tr '\n' ' ' > filtered_files.txt
          echo "::set-output name=filtered_files::$(cat filtered_files.txt)"

      - name: Find Changed Directories
        id: find-changed-dirs
        run: |
          > updated_directories.txt
          for changed_file in $(cat filtered_files.txt); do
            mod_dir=$(dirname "$changed_file")
            updated_dir=$(echo "$mod_dir" | cut -d/ -f1)
            echo "$updated_dir" >> updated_directories.txt
          done
          echo "Below directories have been updated ... "
          cat updated_directories.txt
          echo "Below unique directories were updated ... "
          sort updated_directories.txt | uniq > unique_updated_directories.txt
          cat unique_updated_directories.txt
          echo "::set-output name=changed_dirs::$(cat unique_updated_directories.txt)"

      - name: Zip Lambda Function Code
        if: ${{ steps.find-changed-dirs.outputs.changed_dirs != '' }}
        run: |
          for folder in $(cat unique_updated_directories.txt); do
            echo "Creating zip for $folder"
            cd $folder
            zip -r function.zip ./*
            cd ..
          done

      - name: Publish New Lambda Versions
        if: ${{ steps.find-changed-dirs.outputs.changed_dirs != '' }}
        run: |
          echo "FunctionName,Version,LastModified,Runtime,MemorySize,Timeout" > lambda_versions.csv  # Initialize CSV header
          for folder in $(cat unique_updated_directories.txt); do
            echo "Publishing new version of Lambda in folder: $folder"
            if [ -f "$folder/function.zip" ]; then
              # Update the function code
              aws lambda update-function-code --function-name "$folder" --zip-file fileb://$folder/function.zip

              # Wait for the update to complete
              while true; do
                status=$(aws lambda get-function --function-name "$folder" --query 'Configuration.LastUpdateStatus' --output text)
                if [ "$status" != "InProgress" ]; then
                  break
                fi
                echo "Waiting for update to complete for $folder..."
                sleep 5  # Wait for 5 seconds before checking again
              done

              # Now publish the new version
              NEW_VERSION=$(aws lambda publish-version --function-name "$folder" --query 'Version' --output text)
              echo "New version published: $NEW_VERSION for $folder"

              # Fetch function details
              FUNCTION_DETAILS=$(aws lambda get-function --function-name "$folder" --output json)
              FUNCTION_NAME=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.FunctionName')
              LAST_MODIFIED=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.LastModified')
              RUNTIME=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.Runtime')
              MEMORY_SIZE=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.MemorySize')
              TIMEOUT=$(echo "$FUNCTION_DETAILS" | jq -r '.Configuration.Timeout')

              # Append details to CSV
              echo "$FUNCTION_NAME,$NEW_VERSION,$LAST_MODIFIED,$RUNTIME,$MEMORY_SIZE,$TIMEOUT" >> lambda_versions.csv
            else
              echo "No function.zip found in $folder, skipping..."
            fi
          done

      - name: Upload Lambda Versions to S3
        if: ${{ steps.find-changed-dirs.outputs.changed_dirs != '' }}
        run: |
          aws s3 cp lambda_versions.csv s3://lambda-versioning-data/lambda_versions.csv

  # Additional jobs for deploying lambdas or tracking versions can be added here
